AllCops:
  Exclude:
    - tmp
    - vendor/**/*
Documentation:
  Enabled: false

LineLength:
  Description: 'Limit lines to a more generous 120 characters.'
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Description: 'Limit AbcSize to a more generous 20 upper limit.'
  Enabled: true
  Max: 20
