AllCops:
  Exclude:
    - tmp
    - vendor/**/*
  TargetRubyVersion: 2.7
Documentation:
  Enabled: false

LineLength:
  Description: 'Limit lines to a more generous 180 characters.'
  Enabled: true
  Max: 180

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 155

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - 'spec/*.rb'

Metrics/AbcSize:
  Enabled: false
